// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Apply(arg1, arg2) {
  return window['go']['main']['App']['Apply'](arg1, arg2);
}

export function DismissAlerts() {
  return window['go']['main']['App']['DismissAlerts']();
}

export function GetReport() {
  return window['go']['main']['App']['GetReport']();
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function RemovePackage(arg1) {
  return window['go']['main']['App']['RemovePackage'](arg1);
}

export function SaveAndElevate(arg1, arg2) {
  return window['go']['main']['App']['SaveAndElevate'](arg1, arg2);
}

export function SetDirty(arg1) {
  return window['go']['main']['App']['SetDirty'](arg1);
}

export function SetMaintenance(arg1) {
  return window['go']['main']['App']['SetMaintenance'](arg1);
}

export function SetWatcher(arg1) {
  return window['go']['main']['App']['SetWatcher'](arg1);
}
